CREATE TABLE "deepfish_flows" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"data" text NOT NULL,
	"created_at" bigint NOT NULL,
	"updated_at" bigint NOT NULL,
	"emoji" text NOT NULL,
	"thumbnail" text,
	"nsfw" boolean DEFAULT false NOT NULL,
	"user_id" integer NOT NULL,
	"runs" integer DEFAULT 0 NOT NULL,
	"is_public" boolean DEFAULT false NOT NULL,
	"example_output_type" text,
	"example_output" text
);
--> statement-breakpoint
CREATE TABLE "deepfish_gifts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deepfish_gifts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"uuid" text DEFAULT gen_random_uuid() NOT NULL,
	"sender_id" integer NOT NULL,
	"credits" integer NOT NULL,
	"message" text,
	"image_url" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"claimed" boolean DEFAULT false NOT NULL,
	"claimed_user_id" integer,
	"claimed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "deepfish_gifts_uuid_unique" UNIQUE("uuid")
);
--> statement-breakpoint
CREATE TABLE "deepfish_user_workflows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deepfish_user_workflows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"title" varchar(256) NOT NULL,
	"data" json NOT NULL,
	"runs" integer DEFAULT 0 NOT NULL,
	"nsfw" boolean DEFAULT false NOT NULL,
	"credit_cost" real DEFAULT 1 NOT NULL,
	"keywords" text DEFAULT '' NOT NULL,
	"page_title" varchar(256) DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "deepfish_users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deepfish_users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firstName" varchar(256),
	"lastName" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"replicate_api_key" varchar(256),
	"fal_api_key" varchar(256),
	"subscribed" boolean DEFAULT false NOT NULL,
	"stripe_customer_id" varchar(256),
	"stripe_subscription_id" varchar(256),
	"stripe_price_id" varchar(256),
	"stripe_current_period_end" timestamp,
	"is_over_18" boolean DEFAULT false NOT NULL,
	"clerk_id" text NOT NULL,
	"email" text NOT NULL,
	"api_key" varchar(256),
	"image_url" text,
	"beta" boolean DEFAULT false NOT NULL,
	"credit_balance" real DEFAULT 0 NOT NULL,
	"completed_walkthrough" boolean DEFAULT false NOT NULL,
	"claimed_free_credits" boolean DEFAULT false NOT NULL,
	CONSTRAINT "deepfish_users_clerk_id_unique" UNIQUE("clerk_id"),
	CONSTRAINT "deepfish_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "deepfish_workflow_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deepfish_workflow_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"workflow_id" integer NOT NULL,
	"provider" varchar(50) DEFAULT 'replicate' NOT NULL,
	"ran_with_our_api_key" boolean DEFAULT true NOT NULL,
	"inputs" json,
	"input_hash" varchar(64),
	"output" json,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"error" text,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"ran_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"archived" boolean DEFAULT false NOT NULL,
	"display_name" varchar(256),
	"thumbnail_url" text
);
--> statement-breakpoint
CREATE TABLE "deepfish_workflows" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deepfish_workflows_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"data" json NOT NULL,
	"runs" integer DEFAULT 0 NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"nsfw" boolean DEFAULT false NOT NULL,
	"max_free_runs" integer DEFAULT 1000 NOT NULL,
	"credit_cost" real DEFAULT 1 NOT NULL,
	"keywords" text DEFAULT '' NOT NULL,
	"page_title" varchar(256) DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "deepfish_workflows_title_unique" UNIQUE("title")
);
--> statement-breakpoint
ALTER TABLE "deepfish_flows" ADD CONSTRAINT "deepfish_flows_user_id_deepfish_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."deepfish_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deepfish_gifts" ADD CONSTRAINT "deepfish_gifts_sender_id_deepfish_users_id_fk" FOREIGN KEY ("sender_id") REFERENCES "public"."deepfish_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deepfish_gifts" ADD CONSTRAINT "deepfish_gifts_claimed_user_id_deepfish_users_id_fk" FOREIGN KEY ("claimed_user_id") REFERENCES "public"."deepfish_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deepfish_user_workflows" ADD CONSTRAINT "deepfish_user_workflows_user_id_deepfish_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."deepfish_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deepfish_workflow_runs" ADD CONSTRAINT "deepfish_workflow_runs_user_id_deepfish_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."deepfish_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deepfish_workflow_runs" ADD CONSTRAINT "deepfish_workflow_runs_workflow_id_deepfish_workflows_id_fk" FOREIGN KEY ("workflow_id") REFERENCES "public"."deepfish_workflows"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "flows_user_idx" ON "deepfish_flows" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "flows_updated_idx" ON "deepfish_flows" USING btree ("updated_at");--> statement-breakpoint
CREATE INDEX "flows_public_idx" ON "deepfish_flows" USING btree ("is_public");--> statement-breakpoint
CREATE INDEX "gifts_sender_idx" ON "deepfish_gifts" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "gifts_uuid_idx" ON "deepfish_gifts" USING btree ("uuid");--> statement-breakpoint
CREATE INDEX "gifts_status_idx" ON "deepfish_gifts" USING btree ("status");--> statement-breakpoint
CREATE INDEX "gifts_claimed_user_idx" ON "deepfish_gifts" USING btree ("claimed_user_id");--> statement-breakpoint
CREATE INDEX "user_workflows_user_idx" ON "deepfish_user_workflows" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "user_workflows_user_title_uidx" ON "deepfish_user_workflows" USING btree ("user_id","title");--> statement-breakpoint
CREATE INDEX "clerk_id_idx" ON "deepfish_users" USING btree ("clerk_id");--> statement-breakpoint
CREATE INDEX "email_idx" ON "deepfish_users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "api_key_idx" ON "deepfish_users" USING btree ("api_key");--> statement-breakpoint
CREATE INDEX "workflow_runs_user_idx" ON "deepfish_workflow_runs" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "workflow_runs_workflow_idx" ON "deepfish_workflow_runs" USING btree ("workflow_id");--> statement-breakpoint
CREATE INDEX "workflow_runs_ran_at_idx" ON "deepfish_workflow_runs" USING btree ("ran_at");--> statement-breakpoint
CREATE INDEX "workflow_runs_hash_idx" ON "deepfish_workflow_runs" USING btree ("input_hash");--> statement-breakpoint
CREATE INDEX "workflow_runs_status_idx" ON "deepfish_workflow_runs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "workflow_runs_archived_idx" ON "deepfish_workflow_runs" USING btree ("archived");--> statement-breakpoint
CREATE INDEX "workflows_title_idx" ON "deepfish_workflows" USING btree ("title");
